- hosts: servers
  user: vaclav

  tasks:
    - name: Pull app container.
      docker_image:
        name: "{{item}}"
        repository: docker.pkg.github.com
        tag: latest
      loop:
        - "{{ lookup('env','REPOSITORY') }}"


  vars_files:
    - vars.yml