name: deploy

on:  [push]

jobs:
  image-build:
    name: Build app image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          tags: vaclav/app:latest
  
  run-ansible:
    name: Run ansible
    runs-on: ubuntu-latest
    needs: image-build
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set and run ansible
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_PRIVATE_KEY_FILE: ansible/.ssh/ans_key
          INVENTORY_FILE: ansible/inventory.ini
          ANSIBLE_VAULT_PASSWORD_FILE: ansible/.ansible-vault-password
          ANSIBLE_HOST_KEY_CHECKING: False

          GH_USERNAME: ${{ github.actor }}
          GH_PASS: ${{ github.token }}
          GH_REGISTRY: docker.pkg.github.com
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > $ANSIBLE_VAULT_PASSWORD_FILE
          mkdir ansible/.ssh
          echo "$SSH_KEY" > $ANSIBLE_PRIVATE_KEY_FILE
          chmod 600 $ANSIBLE_PRIVATE_KEY_FILE
          echo "$ANSIBLE_INVENTORY" > $INVENTORY_FILE
          ansible-playbook -i $INVENTORY_FILE ansible/deploy_to_DO.yml
