name: deploy

on:  [push]

env:
  REPOSITORY: ${{ github.repository }}/app

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build app image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: "$REPOSITOR"
          path: app
          tag_with_sha: true
          tag_with_ref: true

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set and run ansible
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_PRIVATE_KEY_FILE: ansible/.ssh/ans_key
          INVENTORY_FILE: ansible/inventory.ini
          ANSIBLE_VAULT_PASSWORD_FILE: ansible/.ansible-vault-password
          ANSIBLE_HOST_KEY_CHECKING: False

        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > $ANSIBLE_VAULT_PASSWORD_FILE
          mkdir ansible/.ssh
          echo "$SSH_KEY" > $ANSIBLE_PRIVATE_KEY_FILE
          chmod 600 $ANSIBLE_PRIVATE_KEY_FILE
          echo "$ANSIBLE_INVENTORY" > $INVENTORY_FILE
          ansible-playbook -i $INVENTORY_FILE ansible/deploy_to_DO.yml
