name: deploy

on:  [push]

env:
  IMAGE_NAME: hexlet-prj-lvl4

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}/latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build app image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: env.REPOSITORY
          path: app

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set and run ansible
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          PRIVATE_KEY_FILE: ansible/.ssh/ans_key
          INVENTORY_FILE: ansible/inventory.ini
          VAULT_PASSWORD_FILES: ansible/.ansible-vault-password
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > $VAULT_PASSWORD_FILES
          mkdir ansible/.ssh
          echo "$SSH_PUB_KEY" > ansible/.ssh/known_hosts
          echo "$SSH_KEY" > $PRIVATE_KEY_FILE
          chmod 600 $PRIVATE_KEY_FILE
          echo "$ANSIBLE_INVENTORY" > $INVENTORY_FILE
          ansible-playbook --vault-password-file $VAULT_PASSWORD_FILES -i $INVENTORY_FILE --key-file $PRIVATE_KEY_FILE ansible/deploy_to_DO.yml
