name: deploy

on:  [push]

env:
  IMAGE_NAME: hexlet-prj-lvl4

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build app image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          path: app
          tag_with_sha: true
          tag_with_ref: true
