name: deploy

on:  [push]

env:
  IMAGE_NAME: hexlet-prj-lvl4

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to github pkg
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build app image
        uses: docker/build-push-action@v2
        with:
          context: app
          file: Dockerfile
          push: true
          tags: ${{ github.repository }}:latest

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set and run ansible
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          ANSIBLE_PRIVATE_KEY_FILE: ansible/.ssh/ans_key
          ANSIBLE_PUBLIC_KEY_FILE: ansible/.ssh/ans_key.pub
          INVENTORY_FILE: ansible/inventory.ini
          ANSIBLE_VAULT_PASSWORD_FILE: ansible/.ansible-vault-password


        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > $ANSIBLE_VAULT_PASSWORD_FILE
          mkdir ansible/.ssh
          ssh-keyscan -H 164.90.165.17 > ansible/.ssh/known_hosts
          echo "$SSH_KEY" > $ANSIBLE_PRIVATE_KEY_FILE
          echo "$SSH_PUB_KEY" > $ANSIBLE_PUBLIC_KEY_FILE
          chmod 600 $ANSIBLE_PRIVATE_KEY_FILE
          echo "$ANSIBLE_INVENTORY" > $INVENTORY_FILE
          ansible-playbook -i $INVENTORY_FILE ansible/deploy_to_DO.yml
